import { ExtraMatchProperties, MatchDto } from './types';
import { PlayerName } from './players';
import { ChampionName, championsStartsWith } from './champions';

export const matchesS1: (MatchDto & ExtraMatchProperties)[] = [
  {
    date: new Date('2022-11-30'),
    effect: 'Class-ism',
    win: 'red',
    mvp: PlayerName.NightRaven,
    ace: PlayerName.JemLem,
    draft: {
      bans: {
        blue: [
          [ChampionName.Aatrox],
          [ChampionName.Jhin],
          [ChampionName.Gangplank],
          [ChampionName.Tristana],
          [ChampionName.Kennen],
        ],
        red: [
          [ChampionName.Mordekaiser],
          [ChampionName.Viktor],
          [ChampionName.Syndra],
          [ChampionName.Lux],
          [ChampionName.Lissandra],
        ],
      },
      picks: {
        blue: [ChampionName.Bard, ChampionName.Taliyah, ChampionName.Amumu, ChampionName.Evelynn],
        red: [ChampionName.Aphelios, ChampionName.Vayne, ChampionName.Graves, ChampionName.Ashe],
      },
    },
    teams: {
      blue: {
        captain: PlayerName.ThePretender,
        players: [
          {
            name: PlayerName.JemLem,
            champion: ChampionName.Bard,
            role: 'top',
            kills: 4,
            deaths: 6,
            assists: 7,
            cs: 136,
          },
          {
            name: PlayerName.ThePretender,
            champion: ChampionName.Evelynn,
            role: 'mid',
            kills: 11,
            deaths: 7,
            assists: 4,
            cs: 165,
          },
          {
            name: PlayerName.CureLemonade,
            champion: ChampionName.Taliyah,
            role: 'bot',
            kills: 1,
            deaths: 7,
            assists: 6,
            cs: 259,
          },
          {
            name: PlayerName.RayOfGayshine,
            champion: ChampionName.Amumu,
            role: 'support',
            kills: 8,
            deaths: 6,
            assists: 3,
            cs: 80,
          },
        ],
      },
      red: {
        captain: PlayerName.Draghau,
        players: [
          {
            name: PlayerName.NightRaven,
            champion: ChampionName.Graves,
            role: 'top',
            kills: 6,
            deaths: 6,
            assists: 6,
            cs: 295,
          },
          {
            name: PlayerName.Taikutsu,
            champion: ChampionName.Aphelios,
            role: 'mid',
            kills: 7,
            deaths: 3,
            assists: 3,
            cs: 228,
          },
          {
            name: PlayerName.Draghau,
            champion: ChampionName.Vayne,
            role: 'bot',
            kills: 13,
            deaths: 4,
            assists: 6,
            cs: 261,
          },
          {
            name: PlayerName.Sewerslvt,
            champion: ChampionName.Ashe,
            role: 'support',
            kills: 0,
            deaths: 11,
            assists: 14,
            cs: 295,
          },
        ],
      },
    },
    dragonSoul: 'ocean',
  },
  {
    date: new Date('2022-12-7'),
    effect: 'Character Bans',
    win: 'red',
    mvp: PlayerName.Sewerslvt,
    ace: PlayerName.Sharpaim,
    draft: {
      bans: {
        blue: [
          championsStartsWith('K'),
          championsStartsWith('V'),
          championsStartsWith('S'),
          championsStartsWith('N'),
          championsStartsWith('J'),
        ],
        red: [
          championsStartsWith('A'),
          championsStartsWith('G'),
          championsStartsWith('T'),
          championsStartsWith('E'),
          championsStartsWith('L'),
        ],
      },
      picks: {
        blue: [ChampionName.Warwick, ChampionName.Jax, ChampionName.Ekko, ChampionName.Xayah],
        red: [ChampionName.Wukong, ChampionName.Ornn, ChampionName.Lux, ChampionName.Pantheon],
      },
    },
    teams: {
      blue: {
        captain: PlayerName.NightRaven,
        players: [
          {
            name: PlayerName.NightRaven,
            champion: ChampionName.Jax,
            role: 'top',
            kills: 4,
            deaths: 6,
            assists: 8,
            cs: 219,
          },
          {
            name: PlayerName.Sharpaim,
            champion: ChampionName.Warwick,
            role: 'jungle',
            kills: 11,
            deaths: 8,
            assists: 8,
            cs: 142,
          },
          {
            name: PlayerName.Taikutsu,
            champion: ChampionName.Ekko,
            role: 'mid',
            kills: 8,
            deaths: 7,
            assists: 6,
            cs: 156,
          },
          {
            name: PlayerName.Draghau,
            champion: ChampionName.Xayah,
            role: 'bot',
            kills: 3,
            deaths: 8,
            assists: 5,
            cs: 232,
          },
        ],
      },
      red: {
        captain: PlayerName.JemLem,
        players: [
          {
            name: PlayerName.JemLem,
            champion: ChampionName.Ornn,
            role: 'top',
            kills: 6,
            deaths: 4,
            assists: 10,
            cs: 177,
          },
          {
            name: PlayerName.ElVaux,
            champion: ChampionName.Wukong,
            role: 'jungle',
            kills: 7,
            deaths: 6,
            assists: 11,
            cs: 203,
          },
          {
            name: PlayerName.ThePretender,
            champion: ChampionName.Lux,
            role: 'mid',
            kills: 5,
            deaths: 7,
            assists: 12,
            cs: 215,
          },
          {
            name: PlayerName.Sewerslvt,
            champion: ChampionName.Pantheon,
            role: 'bot',
            kills: 10,
            deaths: 9,
            assists: 6,
            cs: 157,
          },
        ],
      },
    },
    dragonSoul: 'chemtech',
  },
];
